mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml

spring:
  freemarker:
    settings:
      auto_import: spring.ftl as spring
    charset: UTF-8
    cache: false




logging:
  file: logs/app.log
  level: debug

#No auth  protected
endpoints:
  shutdown:
    sensitive: false
    enabled: true



#server.tomcat.remote_ip_header=x-forwarded-for
server:
  tomcat:
    protocol_header: x-forwarded-proto
  use-forward-headers: true

# config your database config here. 数据库的配置
db:
  url: jdbc:mysql://localhost/world?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password:
#set if comment is open.
blog:
  comment: true
